// <auto-generated />
namespace RepositoryPatterninMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StudentDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202302051106039_StudentDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
